#!/usr/bin/env sh

# Check Privileges

if [ $(whoami) != 'root' ]; then
  YELLOW='\033[1;33m'
  NC='\033[0m'
  echo "${YELLOW}Please run with sudo privileges${NC}"
  exit 1

# Check OS

elif [ $(uname -s) != "Linux" ]; then
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  NC='\033[0m'
  echo "${RED}ERROR: ${YELLOW}You are trying to install this on an unsupported System."
  echo "This Installer is only supported by Linux Distributions.${NC}"
  exit 1

elif [ -d /var/lib/airconnect ]; then
  GREEN='\033[1;32m'
  NC='\033[0m'
  echo "${GREEN}Update AirConnect...${NC}"

  systemctl stop airupnp

  pushd /var/lib/airconnect
  curl --compressed --silent https://api.github.com/repos/philippe44/AirConnect/releases/latest | grep browser_download_url | cut -d '"' -f 4 | xargs curl --compressed --progress-bar -Lo airconnect.zip
  unzip -p airconnect.zip airupnp-linux-$(uname -m) >airupnp-linux-arm
  rm airconnect.zip
  chmod 755 airupnp-linux-arm
  popd

  systemctl daemon-reload
  
  systemctl start airupnp

  systemctl status airupnp
  
else

  GREEN='\033[0;32m'
  NC='\033[0m'
  echo "${GREEN}Install AirConnect...${NC}"

  curl --compressed --progress-bar https://raw.githubusercontent.com/philippe44/AirConnect/c3dfcdb/bin/airupnp-linux-$(uname -m) -o airupnp-linux-arm --output-dir /var/lib/airconnect --create-dirs
  pushd /var/lib/airconnect
  chmod 755 airupnp-linux-arm
  popd

  pushd /etc/systemd/system/
  curl -LO https://raw.githubusercontent.com/pheiduck/rpi_configs/main/airupnp.service
  popd

  systemctl enable --now airupnp

  systemctl status airupnp

fi
