#!/usr/bin/env sh

# Check Privileges

if [ $(whoami) != 'root' ]; then
  YELLOW='\033[1;33m'
  NC='\033[0m'
  echo "${YELLOW}Please run with sudo privileges${NC}"
  exit 1

# Check OS

elif [ $(uname -s) != "Linux" ]; then
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  NC='\033[0m'
  echo "${RED}ERROR: ${YELLOW}You are trying to install this on an unsupported System."
  echo "This Installer is only supported by Linux Distributions.${NC}"
  exit 1

elif [ -d /var/lib/airconnect ]; then
  GREEN='\033[1;32m'
  NC='\033[0m'
  echo "${GREEN}Update AirConnect...${NC}"
  VER="1.7.0"

  systemctl stop airupnp

  pushd /var/lib/airconnect
  curl -LO --compressed --progress-bar https://github.com/philippe44/AirConnect/releases/download/${VER}/AirConnect-${VER}.zip
  unzip -p AirConnect-${VER}.zip airupnp-linux-$(uname -m) >airupnp-linux-arm
  rm AirConnect-*.zip
  chmod 755 airupnp-linux-arm
  popd

  systemctl daemon-reload
  
  systemctl start airupnp

  systemctl status airupnp
  
else

  GREEN='\033[0;32m'
  NC='\033[0m'
  echo "${GREEN}Install AirConnect...${NC}"

  curl --compressed --progress-bar https://raw.githubusercontent.com/philippe44/AirConnect/c3dfcdb/bin/airupnp-linux-$(uname -m) -o airupnp-linux-arm --output-dir /var/lib/airconnect --create-dirs
  pushd /var/lib/airconnect
  chmod 755 airupnp-linux-arm
  popd

  pushd /etc/systemd/system/
  cat > airupnp.service <<EOF
  [Unit]
  Description=AirUPnP bridge
  After=network-online.target
  Wants=network-online.target

  [Service]
  ExecStart=/var/lib/airconnect/airupnp-linux-arm -l 1000:2000 -Z -x /var/lib/airconnect/airupnp.xml
  Restart=on-failure
  RestartSec=30

  [Install]
  WantedBy=multi-user.target
EOF
  popd

  systemctl enable --now airupnp

  systemctl status airupnp

fi
