#!/usr/bin/env sh

if [ $(whoami) != 'root' ]; then
  YELLOW='\033[1;33m'
  NC='\033[0m'
  echo "${YELLOW}Please run with sudo privileges${NC}"
  exit 1
else

export ZSTD_CLEVEL=5
export ZSTD_NBTHREADS=2

backupDate=$(date '+%d%m%y')

for dir in docker/*
do
    pushd ${dir}
    docker-compose stop
    popd
done

sleep 15

pushd /path/to/userhome
tar --create --zstd --file docker-backup-$backupDate.tar.zst docker
scp -O docker-backup-$backupDate.tar.zst Server:path/to/backupdir
popd

sleep 15

for dir in docker/*
do
    pushd ${dir}
    docker-compose start
    popd
done

fi
