#!/usr/bin/env sh
# wake-up-device
# Sends WOL only if the device is not already on (checked via ARP)

# -----------------------
# CONFIGURATION
# -----------------------
MAC="<MAC>"
BROADCAST="<BROADCAST>"
IP="<IP>"  # Device IP in your LAN
# -----------------------

# Check ARP table to see if the device is already online
if arp -an | grep -i "$MAC" >/dev/null 2>&1; then
    printf "Device with MAC %s is already up. Exiting.\n" "$MAC"
    exit 0
fi

printf "Device is not up, sending Wake-on-LAN to MAC %s via %s ...\n" "$MAC" "$BROADCAST"
wakeonlan -i "$BROADCAST" "$MAC"
