#!/usr/bin/env zsh

# Farben für die Ausgabe
YELLOW='\033[1;33m'
NC='\033[0m'

# Backup-Konfiguration
export ZSTD_CLEVEL=9
export ZSTD_NBTHREADS=2
username=$(whoami)
backupDate=$(date '+%d%m%y')

# Docker-Container stoppen
for dir in docker/*
do
    pushd ${dir}
    docker-compose down
    popd
done

sleep 15

# Backup erstellen
pushd /home/$username
sudo tar --create --sparse --zstd --file docker-backup-$backupDate.tar.zst --checkpoint=.100 docker
popd

sleep 15

# Docker-Container wieder starten
for dir in docker/*
do
    pushd ${dir}
    docker-compose up -d
    popd
done

# Nur die drei neuesten Backups behalten
backup_dir="/home/$username"
files=(${backup_dir}/docker-backup-*.tar.zst(Nonom))

if (( ${#files[@]} > 3 )); then
    old_files=("${files[@]:3}")
    for file in "${old_files[@]}"; do
        rm -- "$file"
        printf "${YELLOW}Lösche altes Backup: %s${NC}\n" "$file"
    done
fi


echo "${YELLOW}Backup abgeschlossen.${NC}"
