#!/usr/bin/env sh

# Variables
bindir='/var/lib/airconnect/'
sysdir='/etc/systemd/system/'

# Check Privileges
if [ $(whoami) != 'root' ]; then
  YELLOW='\033[1;33m'
  NC='\033[0m'
  echo "${YELLOW}WARNING: ${NC}Please run with sudo privileges."
  exit 1

# Check OS
elif [ $(uname -s) != "Linux" ]; then
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  NC='\033[0m'
  echo "${RED}ERROR: ${NC}You are trying to install this on an unsupported System.\nThis Installer is only supported by Linux Distributions (w/ systemd)."
  exit 1

elif [ -d "${bindir}" ]; then
  GREEN='\033[1;32m'
  NC='\033[0m'
  echo "${GREEN}Update AirConnect...${NC}"

  systemctl stop airupnp

  pushd "${bindir}"
  curl --compressed --silent https://api.github.com/repos/philippe44/AirConnect/releases/latest | grep browser_download_url | cut -d '"' -f 4 | xargs curl --compressed --progress-bar -Lo airconnect.zip
  unzip -p airconnect.zip airupnp-linux-$(uname -m) >airupnp-linux
  rm airconnect.zip
  chmod 755 airupnp-linux
  popd

  systemctl daemon-reload
  
  systemctl start airupnp

  systemctl status airupnp
  
else

  GREEN='\033[0;32m'
  NC='\033[0m'
  echo "${GREEN}Install AirConnect...${NC}"

  if [ $(grep ^VERSION_ID= /etc/os-release 2> /dev/null | cut -d'=' -f2) >= '11' ]; then
    apt install -y libssl1.1
  fi

  curl --compressed --progress-bar https://raw.githubusercontent.com/philippe44/AirConnect/c3dfcdb/bin/airupnp-linux-$(uname -m) -o airupnp-linux --output-dir "${bindir}" --create-dirs
  pushd "${bindir}"
  chmod 755 airupnp-linux
  popd

  pushd "${sysdir}"
  curl -LO https://raw.githubusercontent.com/pheiduck/rpi_configs/main/airconnect/airupnp.service
  popd

  systemctl daemon-reload

  systemctl enable --now airupnp

  systemctl status airupnp

fi
