#!/usr/bin/env sh

# Variables
bindir='/var/lib/airconnect/'
sysdir='/etc/systemd/system/'

# Check Privileges
if [ $(whoami) != 'root' ]; then
  YELLOW='\033[1;33m'
  NC='\033[0m'
  printf "%s\n" "${YELLOW}WARNING: ${NC}Please run with sudo privileges."
  exit 1

# Check OS
elif [ $(uname -s) != "Linux" ]; then
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  NC='\033[0m'
  printf "%s\n" "${RED}ERROR: ${NC}Don't use the uninstaller on unsupported Systems!\nThis Uninstaller is only supported by Linux Distributions."
  exit 1

elif [ -d "${bindir}" ]; then
  RED='\033[0;31m'
  NC='\033[0m'
  printf "%s\n" "${RED}Uninstall AirConnect...${NC}"

  systemctl disable --now airupnp

  rm -rv "${bindir}"

  rm -v "${sysdir}"airupnp.service

  systemctl daemon-reload

else

  RED='\033[0;31m'
  NC='\033[0m'
  printf "%s\n" "${RED}ERROR: ${NC}AirConnect has already been uninstalled.\nFor reinstall use the installer script."
  exit 1

fi
