name: Linux x86_64
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup ubuntu-24.04
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo sed -i 's/jammy/noble/' /etc/apt/sources.list
      - run: sudo rm -f /etc/apt/sources.list.d/*
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zsh zsh-common
      - uses: actions/checkout@main
      - name: Cache brew
        id: cache-brew
        uses: actions/cache@main
        with:
          path: /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-brew
      - name: Install dependencies
        if: ${{ steps.cache-brew.outputs.cache-hit != 'true' || 'true' }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" 1> /dev/null
          brew reinstall curl 1> /dev/null
          sudo apt-get purge curl -y 1> /dev/null
          sudo ln -s /home/linuxbrew/.linuxbrew/bin/curl /usr/bin/curl
      - name: Testing Shell script
        run: |
          sudo zsh airconnect_installer
          sudo zsh airconnect_installer
          sudo zsh airconnect_uninstaller
