name: Linux x86_64
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Testing Shell script
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install zsh curl 1> /dev/null
          sudo zsh airconnect_installer
          sudo zsh airconnect_installer
          sudo zsh airconnect_uninstaller
