name: Linux x86_64
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zsh zsh-common
      - uses: actions/checkout@main
      - name: Testing Shell script
        run: |
          cd airconnect
          sudo zsh airconnect_installer
          sudo zsh airconnect_installer
          sudo zsh airconnect_uninstaller
          sudo zsh airconnect_uninstaller || true

  other-scripts:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@main

      - name: Run sript 'pihole-cloudflared'
        run: |
          sudo bash pihole-cloudflared

          
      - name: Run sript 'update_fastfetch'
        run: |
          sudo bash update_fastfetch
