name: Linux x86_64
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/*
        if: ${{ matrix.os != 'ubuntu-24.04' }}
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zsh zsh-common
      - uses: actions/checkout@main
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get purge -y curl
          wget https://curl.se/download/curl-7.83.0.tar.xz
          tar xfv curl-7.83.0.tar.xz
          cd curl-7.83.0
          ./configure --with-openssl
          sudo make install
          sudo ldconfig
      - name: Testing Shell script
        run: |
          cd airconnect
          sudo zsh airconnect_installer
          sudo zsh airconnect_installer
          sudo zsh airconnect_uninstaller
          sudo zsh airconnect_uninstaller || true

  pihole-ci:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@main

      - name: Run sript 'pihole-cloudflared.sh'
        run: |
          sudo bash pihole-cloudflared.sh
