name: Linux x86_64
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo rm -f /etc/apt/sources.list.d/*
        if: ${{ matrix.os != 'ubuntu-24.04' }}
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zsh zsh-common
      - uses: actions/checkout@main
      - name: Cache brew
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04' }}
        id: cache-brew
        uses: actions/cache@main
        with:
          path: /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-brew
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04' }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" 2> /dev/null
          export HOMEBREW_NO_ENV_HINTS=1
          brew reinstall curl 2> /dev/null
          sudo apt-get purge curl -y 2> /dev/null
          sudo ln -s /home/linuxbrew/.linuxbrew/bin/curl /usr/bin/curl
      - name: Testing Shell script
        run: |
          cd airconnect
          sudo zsh airconnect_installer
          sudo zsh airconnect_installer
          sudo zsh airconnect_uninstaller
          sudo zsh airconnect_uninstaller || true

  debian-Unittest:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - run: apt-get update && apt-get install -y sudo zsh

      - uses: actions/checkout@main

      - name: Run sript 'pihole-cloudflared.sh'
        run: |
          bash pihole-cloudflared.sh
