name: Linux x86_64
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Run commands
        run: |
          sudo apt update 1> /dev/null
          sudo apt install zsh -y 1> /dev/null
          sudo zsh airconnect_installer
          sudo zsh airconnect_installer
          sudo zsh airconnect_uninstaller
